FROM apache/airflow:3.0.6-python3.11

USER airflow
COPY docker/requirements_airflow.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements_airflow.txt

ENV PYTHONPATH="${PYTHONPATH}:/opt/airflow" 